### ISSUE TITLE
Feature request: Ability to pick see a new package based on build number

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go-ansible#139]
I've gone ahead and went with a blank issue as this is a FR and not a bug. Let me know if anything more is needed here.

As a follow up to being able to have the repository channel be configurable, we have ran into another scenario where it would be beneficial to call out the build number to look for inside the package.

During the Sensu Go QA process for a new release candidate, we are using this Ansible collection to upgrade a long running instance of Sensu Go to mimic customer environments. This lets us both look for possible issues that may not be seen on environments spun up just for QA and also learn about the Ansible collection for supporting customers that are or may eventually use it.

When we upgrade our long running instance as part of the QA process, if bug is found, currently only the version of the package is looked at by Ansible. The new release candidate only has the build number changed as fixes are put in, so Ansible doesn't see anything "new". While not all bugs will warrant another upgrade of this long running instance, as it stands I have to downgrade to the old version and re-upgrade to the new build to get a new release candidate installed.

Is it possibly to have Ansible, either in the collection or in Ansible core, to detect the build number of the package? It would appear for at least `yum` the release field is what contains this:

```
Name        : sensu-go-backend
Arch        : x86_64
Version     : 5.15.0
Release     : 7782
Size        : 35 M
Repo        : installed
From repo   : sensu_stable
Summary     : Sensu Go Backend
URL         : https://sensu.io
License     : Proprietary
Description : Sensu Go Backend
```

I took a quick look around and only found this area to have that added:

https://github.com/sensu/sensu-go-ansible/blob/master/roles/install/tasks/main.yml#L10-L17

But I don't know how you would default the build number or maybe you would need a conditional that if it is null, don't look at it. Also don't know if there are python things to make this worth either.

**Comment by tadeboro** [comment]
Let us assume that we use the following playbook for installing backend package:

```
- hosts: backends
  become: true

  tasks:
    - name: Install backend
      include_role:
        name: sensu.sensu_go.install
      vars:
        components: [sensu-go-backend]
        version: 5.16.0
        channel: testing
```

When we run this playbook against a host that has no `sensu-go-backend` package installed or the currently installed version is not equal to the `5.16.0`, Ansible will install the latest `5.16.0` build that is currently available.

If we then push a new `5.16.0` build to the Sensu testing repository and re-run the playbook, Ansible will say that there is nothing to do since we already have `5.16.0` installed. And this is not what we want. We want this command to install that latest build even if the version did not change. Is this correct or am I misunderstanding the problem?

I see two different "degrees" of solving this issue. If we do not care about the specific builds, we can simply redefine the semantics of the `Install backend` task that was shown in the example from *Make sure that **arbitrary** build of the specific version is installed* to *Make sure that **the latest** build of the specific version is installed*. This is a five-minute fix (+ two hours to add integration tests and documentation).

We can take things a bit further and make build a first-class citizen in our collection. What I mean by this is adding the ability to install a selected build of the package, not just the latest one available at the moment. We would need to add another variable to the `install` role that would control the build version. We would, of course, set the default value to something that would mean *the latest build currently available* in order to keep the role as straightforward to use in common scenarios as possible. This is a two-hour fix (+ half an hour to add unit/integration tests and documentation - having build variable available simplifies the testing substantially ;).
