### ISSUE TITLE
documentation of `name` is unclear

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go-ansible#182]
**Bug description**

the module documentation is bit unclear.

In [check – Manage Sensu checks](https://sensu.github.io/sensu-go-ansible/modules/check.html), `name` is described as:

> The Sensu object’s name.

which is unclear. it is used as a unique ID, shown in the web UI, and has some restrictions (special characters are not allowed, such as spaces).

as such, when you need to modify `name`, you must create another task to remove the old one, and the play fails when `name` contains special characters.

**How to reproduce the bug**

1. rename a check, say, `check` to `new-check`, or `new check`.
1. the play creates a duplicated check, or fails.

**Expected result**

the doc clearly states that:

* `name` is an unique ID, which implies that, when you change it, you also need to remove old one.
* how `name` is used
* what restrictions it has (and a link to where you should look at)

**Actual result**

the doc simply says:

> The Sensu object’s name.

**Component versions**
 - Ansible Version 2.9.7
 - Sensu Go Collection Version 1.3.1
 - Sensu Go Backend Version 5.19.1

**Additional context**

n/a

**Comment by tadeboro** [comment]
We will update the name description to be more explicit about the role it plays on the backend.

Documenting valid names is a bit more complex because:

 1. Sensu Go docs do not define this (at least I did not manage to find this defined anywhere) and
 2. the validity of the name depends on the Sensu Go version that is being managed.

I know the regex used to validate the names is available at https://github.com/sensu/sensu-go/blob/c031fe6540d225ffb2f76f978d8509fda064e967/api/core/v2/validators.go#L14, but this is not something end-users should look at. Do you happen to know any other source of information about the valid resource names, @trombik?

**Comment by trombik** [comment]
this?

https://docs.sensu.io/sensu-go/latest/reference/checks/#metadata-attributes

probably it is not a good idea to document the regex in the module documentation, maybe something like:

> the name is used in metadata `name`. name must be unique in a `namespace`, and other restrictions apply. see https://docs.sensu.io/sensu-go/latest/reference/checks/#metadata-attributes for details. note that you cannot _rename_ a resource. when you _rename_ it, the module creates a new resource and the old resource will _NOT_ be removed.

**Comment by tadeboro** [comment]
We just merged the changes that should clarify the role that the name parameter has. The one thing we did not document is rename behavior. This is such a basic Ansible concept that has no place in the collection documentation.

**Comment by trombik** [comment]
great.
