### ISSUE TITLE
Password-hash support

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go-ansible#217]
Do we currently have support for providing a `password_hash` as _input_ to the Ansible Collection? 

It looks like the collection does currently use `password_hash` for creating/updating users, but [it seems to consume a plaintext password that it then encrypts using Bcrypt](https://github.com/sensu/sensu-go-ansible/blob/master/plugins/modules/user.py#L97-L114). What if the user wants to provide pre-hashed passwords out of band of Ansible? Is that already supported?

**Comment by tadeboro** [comment]
Currently, it is not possible to provide a hashed password. There are two reasons for the current lack of support:

 1. Sensu Go < 5.21 knows noting about hashes and we still support those versions.
 2. No one asked for this kind of functionality yet.

If using password hashes is something that we would like to support, we can add it to the collection in a backward-compatible way. We would introduce a `password_hash` parameter to the `sensu.sensu_go.user` module and make it mutually exclusive with the `password` field.

But there is one problem: change detection. Right now, there is no way to detect if the password changed when the user supplies a password hash. The [user API endpoint][(https://docs.sensu.io/sensu-go/latest/api/users/#usersuser-get) does not provide enough information about the user (it is missing a password hash). We can check for change when the user provides a plain text password since we can hit the [auth test](https://docs.sensu.io/sensu-go/latest/api/auth/#authtest-get) API endpoint, but if we only get a hash, this is not an option.

So, I see a few different ways forward.

 1. We keep using the plaintext password and add a prominent section about securing secrets in Ansible playbooks to the documentation (for example, a fully working Ansible vault sample).
 2. We add a `password_hash` parameter to the `sensu.sensu_go.user` module and document that task invocations using that parameter is not idempotent and will always return `chaged: true` in the result.
 3. Probably the best option would be if Sensu Go API would start returning password hash and enable us to implement proper change detection. This would remove the lack of idempotence from the second proposed approach.
 4. It would also be OK if the [reset password API endpoint](https://docs.sensu.io/sensu-go/latest/api/users/#usersuserresetpassword-put) returned back an indication about the password change.

And one more thing: change detection will never be 100% correct because there are at least 2 widely used bcrypt versions in the wild: 2a and 2b. Python implementation by default uses a more recent 2b variant while Go implementation that Sensu Go uses defaults to 2a. This means that the same password will result in a different hash depending on what piece of software is producing it. And we did not even start talking about the bcrypt algo parameters ;)
