### ISSUE TITLE
README needs some additional clarity regarding Ansible 2.8 & Mazer

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go-ansible#86]
Currently if I am looking to use this collection, I'm directed to use Mazer. Upon heading to Ansible's documentation using Mazer, I'm informed that it is deprecated and to use Ansible 2.9. While it's possible to upgrade Ansible using pip, the reality is that for any user who's using Redhat and/or Ansible tower, Ansible 2.9 isn't readily available, so using Mazer is the only option...but this results in a bit of a circular dependency. 

The last documentation available on installing mazer I could find is here: https://github.com/ansible/galaxy/blob/e6030874286a79fd94e83b92f37ad450682e9742/docs/docsite/rst/mazer/install.rst. Would it be possible to add this to the README so that we're not chasing our tails?

**Comment by tadeboro** [comment]
Collections are a technological preview feature of Ansible 2.8 and should not be used in production. We only added `mazer` instructions because people were interested in testing this collection and had no access to Ansible 2.9.

Once Ansible 2.9 is released (in the first half of November, if all goes well), there should be no need to have `mazer` documented at all.

As for the Ansible Tower, Red Hat people who attended our talk about creating and maintaining Ansible collections said that Ansible Tower would be able to install Ansible collections automatically once they are supported.

I will keep this issue open until Ansible 2.9 is released to remind us to update the docs.

**Comment by asachs01** [comment]
👍 thanks @tadeboro !

**Comment by jaredledvina** [comment]
Ansible 2.9 was released today! 
https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst#v2-9-0 & https://groups.google.com/forum/#!topic/ansible-announce/chcjYohq6dA 🎉

**Comment by tadeboro** [comment]
We removed all mazer references while we were doing some cleanup in https://github.com/sensu/sensu-go-ansible/commit/b1a7c7d591fa5ee71a647ef5394a2d5c68b50ec9. We also prepared a `0.7.8` release that contains updated README file.
